/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PodborRouteImport } from './routes/podbor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as CountrySlugRouteImport } from './routes/country.$slug'
import { Route as CardsSlugRouteImport } from './routes/cards.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PodborRoute = PodborRouteImport.update({
  id: '/podbor',
  path: '/podbor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSlugRoute = CardsSlugRouteImport.update({
  id: '/cards/$slug',
  path: '/cards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/podbor': typeof PodborRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/podbor': typeof PodborRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/podbor': typeof PodborRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/podbor'
    | '/sitemap.xml'
    | '/cards/$slug'
    | '/country/$slug'
    | '/service/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/podbor'
    | '/sitemap.xml'
    | '/cards/$slug'
    | '/country/$slug'
    | '/service/$slug'
  id:
    | '__root__'
    | '/'
    | '/podbor'
    | '/sitemap.xml'
    | '/cards/$slug'
    | '/country/$slug'
    | '/service/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodborRoute: typeof PodborRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CardsSlugRoute: typeof CardsSlugRoute
  CountrySlugRoute: typeof CountrySlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podbor': {
      id: '/podbor'
      path: '/podbor'
      fullPath: '/podbor'
      preLoaderRoute: typeof PodborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$slug': {
      id: '/cards/$slug'
      path: '/cards/$slug'
      fullPath: '/cards/$slug'
      preLoaderRoute: typeof CardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodborRoute: PodborRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CardsSlugRoute: CardsSlugRoute,
  CountrySlugRoute: CountrySlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
