/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelCardsRouteImport } from './routes/travel-cards'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PodborRouteImport } from './routes/podbor'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ForeignVirtualCardsRouteImport } from './routes/foreign-virtual-cards'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as CardsForSubscriptionsRouteImport } from './routes/cards-for-subscriptions'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CryptoIndexRouteImport } from './routes/crypto.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BanksIndexRouteImport } from './routes/banks.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as CryptoSlugRouteImport } from './routes/crypto.$slug'
import { Route as CountrySlugRouteImport } from './routes/country.$slug'
import { Route as CardsSlugRouteImport } from './routes/cards.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BanksSlugRouteImport } from './routes/banks.$slug'
import { Route as AiSlugRouteImport } from './routes/ai.$slug'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCryptoRouteImport } from './routes/admin.crypto'
import { Route as AdminCardsRouteImport } from './routes/admin.cards'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBanksRouteImport } from './routes/admin.banks'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as CardsSlugReviewsRouteImport } from './routes/cards.$slug_.reviews'

const TravelCardsRoute = TravelCardsRouteImport.update({
  id: '/travel-cards',
  path: '/travel-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PodborRoute = PodborRouteImport.update({
  id: '/podbor',
  path: '/podbor',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeignVirtualCardsRoute = ForeignVirtualCardsRouteImport.update({
  id: '/foreign-virtual-cards',
  path: '/foreign-virtual-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsForSubscriptionsRoute = CardsForSubscriptionsRouteImport.update({
  id: '/cards-for-subscriptions',
  path: '/cards-for-subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoIndexRoute = CryptoIndexRouteImport.update({
  id: '/crypto/',
  path: '/crypto/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksIndexRoute = BanksIndexRouteImport.update({
  id: '/banks/',
  path: '/banks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoSlugRoute = CryptoSlugRouteImport.update({
  id: '/crypto/$slug',
  path: '/crypto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSlugRoute = CardsSlugRouteImport.update({
  id: '/cards/$slug',
  path: '/cards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksSlugRoute = BanksSlugRouteImport.update({
  id: '/banks/$slug',
  path: '/banks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSlugRoute = AiSlugRouteImport.update({
  id: '/ai/$slug',
  path: '/ai/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCryptoRoute = AdminCryptoRouteImport.update({
  id: '/admin/crypto',
  path: '/admin/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/admin/cards',
  path: '/admin/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBanksRoute = AdminBanksRouteImport.update({
  id: '/admin/banks',
  path: '/admin/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSlugReviewsRoute = CardsSlugReviewsRouteImport.update({
  id: '/cards/$slug_/reviews',
  path: '/cards/$slug/reviews',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/cards-for-subscriptions': typeof CardsForSubscriptionsRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/foreign-virtual-cards': typeof ForeignVirtualCardsRoute
  '/methodology': typeof MethodologyRoute
  '/partners': typeof PartnersRoute
  '/podbor': typeof PodborRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel-cards': typeof TravelCardsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/banks': typeof AdminBanksRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/crypto': typeof AdminCryptoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/ai/$slug': typeof AiSlugRoute
  '/banks/$slug': typeof BanksSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/crypto/$slug': typeof CryptoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/banks/': typeof BanksIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/crypto/': typeof CryptoIndexRoute
  '/cards/$slug/reviews': typeof CardsSlugReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/cards-for-subscriptions': typeof CardsForSubscriptionsRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/foreign-virtual-cards': typeof ForeignVirtualCardsRoute
  '/methodology': typeof MethodologyRoute
  '/partners': typeof PartnersRoute
  '/podbor': typeof PodborRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel-cards': typeof TravelCardsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/banks': typeof AdminBanksRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/crypto': typeof AdminCryptoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/ai/$slug': typeof AiSlugRoute
  '/banks/$slug': typeof BanksSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/crypto/$slug': typeof CryptoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ai': typeof AiIndexRoute
  '/banks': typeof BanksIndexRoute
  '/blog': typeof BlogIndexRoute
  '/crypto': typeof CryptoIndexRoute
  '/cards/$slug/reviews': typeof CardsSlugReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/cards-for-subscriptions': typeof CardsForSubscriptionsRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/foreign-virtual-cards': typeof ForeignVirtualCardsRoute
  '/methodology': typeof MethodologyRoute
  '/partners': typeof PartnersRoute
  '/podbor': typeof PodborRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel-cards': typeof TravelCardsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/banks': typeof AdminBanksRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/crypto': typeof AdminCryptoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/ai/$slug': typeof AiSlugRoute
  '/banks/$slug': typeof BanksSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/crypto/$slug': typeof CryptoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/banks/': typeof BanksIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/crypto/': typeof CryptoIndexRoute
  '/cards/$slug_/reviews': typeof CardsSlugReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/cards-for-subscriptions'
    | '/editorial-policy'
    | '/foreign-virtual-cards'
    | '/methodology'
    | '/partners'
    | '/podbor'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/travel-cards'
    | '/admin/ai'
    | '/admin/banks'
    | '/admin/blog'
    | '/admin/cards'
    | '/admin/crypto'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/seo'
    | '/ai/$slug'
    | '/banks/$slug'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/country/$slug'
    | '/crypto/$slug'
    | '/guides/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/service/$slug'
    | '/admin/'
    | '/ai/'
    | '/banks/'
    | '/blog/'
    | '/crypto/'
    | '/cards/$slug/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/cards-for-subscriptions'
    | '/editorial-policy'
    | '/foreign-virtual-cards'
    | '/methodology'
    | '/partners'
    | '/podbor'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/travel-cards'
    | '/admin/ai'
    | '/admin/banks'
    | '/admin/blog'
    | '/admin/cards'
    | '/admin/crypto'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/seo'
    | '/ai/$slug'
    | '/banks/$slug'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/country/$slug'
    | '/crypto/$slug'
    | '/guides/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/service/$slug'
    | '/admin'
    | '/ai'
    | '/banks'
    | '/blog'
    | '/crypto'
    | '/cards/$slug/reviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/cards-for-subscriptions'
    | '/editorial-policy'
    | '/foreign-virtual-cards'
    | '/methodology'
    | '/partners'
    | '/podbor'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/travel-cards'
    | '/admin/ai'
    | '/admin/banks'
    | '/admin/blog'
    | '/admin/cards'
    | '/admin/crypto'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/seo'
    | '/ai/$slug'
    | '/banks/$slug'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/country/$slug'
    | '/crypto/$slug'
    | '/guides/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/service/$slug'
    | '/admin/'
    | '/ai/'
    | '/banks/'
    | '/blog/'
    | '/crypto/'
    | '/cards/$slug_/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  CardsForSubscriptionsRoute: typeof CardsForSubscriptionsRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  ForeignVirtualCardsRoute: typeof ForeignVirtualCardsRoute
  MethodologyRoute: typeof MethodologyRoute
  PartnersRoute: typeof PartnersRoute
  PodborRoute: typeof PodborRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TravelCardsRoute: typeof TravelCardsRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminBanksRoute: typeof AdminBanksRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminCryptoRoute: typeof AdminCryptoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AiSlugRoute: typeof AiSlugRoute
  BanksSlugRoute: typeof BanksSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CardsSlugRoute: typeof CardsSlugRoute
  CountrySlugRoute: typeof CountrySlugRoute
  CryptoSlugRoute: typeof CryptoSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AiIndexRoute: typeof AiIndexRoute
  BanksIndexRoute: typeof BanksIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CryptoIndexRoute: typeof CryptoIndexRoute
  CardsSlugReviewsRoute: typeof CardsSlugReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel-cards': {
      id: '/travel-cards'
      path: '/travel-cards'
      fullPath: '/travel-cards'
      preLoaderRoute: typeof TravelCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podbor': {
      id: '/podbor'
      path: '/podbor'
      fullPath: '/podbor'
      preLoaderRoute: typeof PodborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreign-virtual-cards': {
      id: '/foreign-virtual-cards'
      path: '/foreign-virtual-cards'
      fullPath: '/foreign-virtual-cards'
      preLoaderRoute: typeof ForeignVirtualCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards-for-subscriptions': {
      id: '/cards-for-subscriptions'
      path: '/cards-for-subscriptions'
      fullPath: '/cards-for-subscriptions'
      preLoaderRoute: typeof CardsForSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/': {
      id: '/crypto/'
      path: '/crypto'
      fullPath: '/crypto/'
      preLoaderRoute: typeof CryptoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks/': {
      id: '/banks/'
      path: '/banks'
      fullPath: '/banks/'
      preLoaderRoute: typeof BanksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/$slug': {
      id: '/crypto/$slug'
      path: '/crypto/$slug'
      fullPath: '/crypto/$slug'
      preLoaderRoute: typeof CryptoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$slug': {
      id: '/cards/$slug'
      path: '/cards/$slug'
      fullPath: '/cards/$slug'
      preLoaderRoute: typeof CardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks/$slug': {
      id: '/banks/$slug'
      path: '/banks/$slug'
      fullPath: '/banks/$slug'
      preLoaderRoute: typeof BanksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$slug': {
      id: '/ai/$slug'
      path: '/ai/$slug'
      fullPath: '/ai/$slug'
      preLoaderRoute: typeof AiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crypto': {
      id: '/admin/crypto'
      path: '/admin/crypto'
      fullPath: '/admin/crypto'
      preLoaderRoute: typeof AdminCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/admin/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banks': {
      id: '/admin/banks'
      path: '/admin/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AdminBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$slug_/reviews': {
      id: '/cards/$slug_/reviews'
      path: '/cards/$slug/reviews'
      fullPath: '/cards/$slug/reviews'
      preLoaderRoute: typeof CardsSlugReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  CardsForSubscriptionsRoute: CardsForSubscriptionsRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  ForeignVirtualCardsRoute: ForeignVirtualCardsRoute,
  MethodologyRoute: MethodologyRoute,
  PartnersRoute: PartnersRoute,
  PodborRoute: PodborRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TravelCardsRoute: TravelCardsRoute,
  AdminAiRoute: AdminAiRoute,
  AdminBanksRoute: AdminBanksRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminCryptoRoute: AdminCryptoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AiSlugRoute: AiSlugRoute,
  BanksSlugRoute: BanksSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CardsSlugRoute: CardsSlugRoute,
  CountrySlugRoute: CountrySlugRoute,
  CryptoSlugRoute: CryptoSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AiIndexRoute: AiIndexRoute,
  BanksIndexRoute: BanksIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CryptoIndexRoute: CryptoIndexRoute,
  CardsSlugReviewsRoute: CardsSlugReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
