/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PodborRouteImport } from './routes/podbor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BanksIndexRouteImport } from './routes/banks.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as CountrySlugRouteImport } from './routes/country.$slug'
import { Route as CardsSlugRouteImport } from './routes/cards.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BanksSlugRouteImport } from './routes/banks.$slug'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCardsRouteImport } from './routes/admin.cards'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBanksRouteImport } from './routes/admin.banks'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PodborRoute = PodborRouteImport.update({
  id: '/podbor',
  path: '/podbor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksIndexRoute = BanksIndexRouteImport.update({
  id: '/banks/',
  path: '/banks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSlugRoute = CardsSlugRouteImport.update({
  id: '/cards/$slug',
  path: '/cards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksSlugRoute = BanksSlugRouteImport.update({
  id: '/banks/$slug',
  path: '/banks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/admin/cards',
  path: '/admin/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBanksRoute = AdminBanksRouteImport.update({
  id: '/admin/banks',
  path: '/admin/banks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/podbor': typeof PodborRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/banks': typeof AdminBanksRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/banks/$slug': typeof BanksSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/banks/': typeof BanksIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/podbor': typeof PodborRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/banks': typeof AdminBanksRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/banks/$slug': typeof BanksSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/admin': typeof AdminIndexRoute
  '/banks': typeof BanksIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/podbor': typeof PodborRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/banks': typeof AdminBanksRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/banks/$slug': typeof BanksSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/banks/': typeof BanksIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/podbor'
    | '/sitemap.xml'
    | '/admin/banks'
    | '/admin/blog'
    | '/admin/cards'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/seo'
    | '/banks/$slug'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/country/$slug'
    | '/guides/$slug'
    | '/service/$slug'
    | '/admin/'
    | '/banks/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/podbor'
    | '/sitemap.xml'
    | '/admin/banks'
    | '/admin/blog'
    | '/admin/cards'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/seo'
    | '/banks/$slug'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/country/$slug'
    | '/guides/$slug'
    | '/service/$slug'
    | '/admin'
    | '/banks'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/podbor'
    | '/sitemap.xml'
    | '/admin/banks'
    | '/admin/blog'
    | '/admin/cards'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/seo'
    | '/banks/$slug'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/country/$slug'
    | '/guides/$slug'
    | '/service/$slug'
    | '/admin/'
    | '/banks/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PodborRoute: typeof PodborRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminBanksRoute: typeof AdminBanksRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  BanksSlugRoute: typeof BanksSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CardsSlugRoute: typeof CardsSlugRoute
  CountrySlugRoute: typeof CountrySlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BanksIndexRoute: typeof BanksIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podbor': {
      id: '/podbor'
      path: '/podbor'
      fullPath: '/podbor'
      preLoaderRoute: typeof PodborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks/': {
      id: '/banks/'
      path: '/banks'
      fullPath: '/banks/'
      preLoaderRoute: typeof BanksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$slug': {
      id: '/cards/$slug'
      path: '/cards/$slug'
      fullPath: '/cards/$slug'
      preLoaderRoute: typeof CardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks/$slug': {
      id: '/banks/$slug'
      path: '/banks/$slug'
      fullPath: '/banks/$slug'
      preLoaderRoute: typeof BanksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/admin/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banks': {
      id: '/admin/banks'
      path: '/admin/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AdminBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PodborRoute: PodborRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminBanksRoute: AdminBanksRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoRoute: AdminSeoRoute,
  BanksSlugRoute: BanksSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CardsSlugRoute: CardsSlugRoute,
  CountrySlugRoute: CountrySlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BanksIndexRoute: BanksIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
